### PR TITLE
Updating to 58.0.3005.0

### PR DESCRIPTION
**Pull request by yangfanud**

### CODE REVIEW

**Comment by yangfanud** [comment]
Updating to 58.0.3005.0

**Comment by yangfanud** [comment]
I think I remove all these generated files from previous commit?

**Comment by rjshade** [comment]
Nope, there are still files in src/net/quic/chromium/out and src/net/out which shouldn't be there. Have you pushed your local commits to github? You can confirm by looking at the list of files in https://github.com/google/proto-quic/pull/35/files

**Comment by yangfanud** [comment]
No, I have not pushed yet.

**Comment by rjshade** [comment]
I'm confused:

Why was https://github.com/google/proto-quic/commit/5297fd417bdf2626abdd16fcd740f74ab0588f69 committed without review?

Why was this committed without review? Is it a revert of https://github.com/google/proto-quic/commit/5297fd417bdf2626abdd16fcd740f74ab0588f69 or is it the latest version of proto-quic?

Can we reset the tree to before https://github.com/google/proto-quic/commit/5297fd417bdf2626abdd16fcd740f74ab0588f69 and do the review from that point (without all the files in out/)? It's impossible to review a >3000 file pull request on github.

**Comment by rjshade** [comment]
Conclusion: the github repository history UI is confusing, as is the code review UI. I think we're good here, with the reminder that in future cleanups (such as deleting accidentally added build files) should be done as standalone commits.

**Comment by yangfanud** [comment]
Thank you so much, Robbie.

**Pull request merged**
