### PR TITLE
Updating to 56.0.2912.0

### PR DESCRIPTION
**Pull request by yangfanud**

### CODE REVIEW

**Comment by janaiyengar** [comment]
Can you uncomment the quartc source files (including tests) added in net/net.gypi?

**Comment by rjshade** [comment]
And remove the comments from BUILD.gn (or remove the lines if :balsa is no longer a dependency). There are a few additions of:

#      ":balsa",

**Comment by yangfanud** [comment]
Uncommenting quartc files and delete #balsa.

**Comment by notedit** [comment]
what quartc  is for?    webrtc?

**Comment by janaiyengar** [comment]
Thanks, Fan! Please merge with "squash and merge".
notedit: quartc is an API that QUIC exposes, with a long-term plan to try webrtc integration (as you already figured out!).

**Pull request merged**
